inp1 = str(input("What is your partition ?: "))
inp2 = str(input("What is your sevice ?: "))
inp3 = str(input("What is your region ?: "))
inp4 = int(input("What is your account-id?: "))
inp5 = int(input("What is your resource-id?: "))
output_str = "arn:" + inp1 + ":" + inp2 + ":" + inp3 + ":" + str(inp4) + ":" + str(inp5)
print(output_str)
